### ISSUE TITLE
could not determine kind of name for C.** under window 7 (32bit)

### ISSUE THREAD

**Issue by anjieych** [karalabe/hid#14]
C:\Users\Frank>go install github.com/karalabe/hid
# github.com/karalabe/hid
d:\go\src\github.com\karalabe\hid\hid_enabled.go:133:10: could not determine kind of name for C.hid_device
d:\go\src\github.com\karalabe\hid\hid_enabled.go:174:61: could not determine kind of name for C.size_t
d:\go\src\github.com\karalabe\hid\hid_enabled.go:174:39: could not determine kind of name for C.uchar
d:\go\src\github.com\karalabe\hid\hid_enabled.go:82:26: could not determine kind of name for C.ushort
`

C:\Users\Frank>go get github.com/karalabe/hid
# github.com/karalabe/hid
d:\go\src\github.com\karalabe\hid\hid_enabled.go:133:10: could not determine kind of name for C.hid_device
d:\go\src\github.com\karalabe\hid\hid_enabled.go:174:61: could not determine kind of name for C.size_t
d:\go\src\github.com\karalabe\hid\hid_enabled.go:174:39: could not determine kind of name for C.uchar
d:\go\src\github.com\karalabe\hid\hid_enabled.go:82:26: could not determine kind of name for C.ushort

**Comment by anjieych** [comment]
It works well under window7 (64bit). So,what should I do to make it works well under window7 (32bit)?
Help me please.

**Comment by karalabe** [comment]
AppVeyor tests for 32 bit builds too, so something must be off at your end https://ci.appveyor.com/project/karalabe/hid

Do you have the MingW environment set up for building C/CGO sources?

**Comment by fjl** [comment]
This build error is an issue with the Go toolchain. We can't do anything about this.
