### ISSUE TITLE
Compile error on ubuntu18

### ISSUE THREAD

**Issue by edulop91** [karalabe/hid#27]
```
# github.com/karalabe/hid
vendor/github.com/karalabe/hid/hid_enabled.go:23:11: fatal error: os/threads_posix.c: No such file or directory
  #include "os/threads_posix.c"
           ^~~~~~~~~~~~~~~~~~~~
```
Have been getting this on ubuntu18. CGO_ENABLED=1. libusb 1.0.0 + libusb1.0.0-dev installed.

Wondering what I'm missing

**Comment by filinvadim** [comment]
Vendoring does not hook C files.

**Comment by devfacet** [comment]
It is related to https://github.com/golang/go/issues/26366 . Any chance you could add dummy files into `hidapi` and `libusb` directories. Here are examples:
- https://github.com/golang/go/issues/26366#issuecomment-606404010
- https://github.com/go-gl/glfw/pull/258

Thanks

**Comment by dolmen** [comment]
~#31 should fix that.~

Edit: it doesn't.

**Comment by dolmen** [comment]
I have [a fix for this issue](https://github.com/dolmen-go/hid/commit/ae6e6ef1b126c15a70fcededd7d39499b17864f5) on my fork: [github.com/dolmen-go/hid](https://github.com/dolmen-go/hid).

**Comment by holiman** [comment]
Fixed with hidapi upgrade
